version: '3'

# networks:
#   private_network:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.19.0.0/16

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    # env_file:
    #   - .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
    # networks:
    #   private_network:
    #     ipv4_address: 172.19.0.5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf

